# Generated by Django 2.2.16 on 2021-03-31 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serase_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divida',
            name='juros_tipo',
            field=models.CharField(choices=[('composto', 'composto'), ('simples', 'simples'), ('não ativo', 'não ativo')], default='não ativo', max_length=9),
        ),
    ]
