# Generated by Django 3.1.3 on 2020-11-12 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serase_app', '0003_auto_20201111_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padraomovimentacao',
            name='dia_cobranca',
            field=models.IntegerField(),
        ),
    ]
