# Generated by Django 3.1.3 on 2020-11-12 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serase_app', '0008_movimentacao_cod_padraomovimentacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='valor_esperado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='valor_pago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
