# Generated by Django 2.2.16 on 2020-11-19 13:51
# But edited by jv_eumsmo after it :)

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serase_app', '0011_auto_20201112_2140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimentacao',
            old_name='categoria',
            new_name='cod_categoria',
        ),
        migrations.RenameField(
            model_name='movimentacao',
            old_name='usuario',
            new_name='cod_usuario',
        ),
        migrations.RenameField(
            model_name='padraomovimentacao',
            old_name='categoria',
            new_name='cod_categoria',
        ),
        migrations.RenameField(
            model_name='padraomovimentacao',
            old_name='usuario',
            new_name='cod_usuario',
        ),
        migrations.RenameField(
            model_name='saldo',
            old_name='usuario',
            new_name='cod_usuario',
        ),
        migrations.RenameField(
            model_name='movimentacao',
            old_name='cod_PadraoMovimentacao',
            new_name='cod_padrao',
        ),
    ]
