# Generated by Django 2.2.16 on 2021-03-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serase_app', '0017_auto_20210315_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padraomovimentacao',
            name='data_geracao',
            field=models.DateField(auto_now_add=True, default='2021-03-01'),
            preserve_default=False,
        ),
    ]
