# Generated by Django 2.2.16 on 2021-03-26 19:49

import datetime
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serase_app', '0019_auto_20210317_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divida',
            name='cod_padrao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serase_app.PadraoMovimentacao'),
        ),
        migrations.AlterField(
            model_name='divida',
            name='credor',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='divida',
            name='juros_tipo',
            field=models.CharField(choices=[('composto', 'composto'), ('simples', 'simples'), ('não ativo', 'não ativo')], default='não ativo', max_length=8),
        ),
        migrations.AlterField(
            model_name='divida',
            name='valor_divida',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='divida',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9),
        ),
        migrations.AlterField(
            model_name='padraomovimentacao',
            name='data_geracao',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
