# Generated by Django 3.1.3 on 2020-11-12 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serase_app', '0002_auto_20201111_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='data_geracao',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='data_lancamento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='descricao',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='padraomovimentacao',
            name='data_fim',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='padraomovimentacao',
            name='data_inicio',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='padraomovimentacao',
            name='descricao',
            field=models.TextField(null=True),
        ),
    ]
