# Generated by Django 3.1.3 on 2020-11-12 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serase_app', '0004_auto_20201111_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padraomovimentacao',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
    ]
