# Generated by Django 3.1.3 on 2020-11-12 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serase_app', '0005_auto_20201111_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='data_geracao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='data_lancamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='descricao',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='padraomovimentacao',
            name='data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='padraomovimentacao',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
