# Generated by Django 3.1.3 on 2020-11-12 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serase_app', '0006_auto_20201111_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padraomovimentacao',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
