# Generated by Django 3.1.3 on 2020-11-12 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serase_app', '0007_auto_20201111_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='cod_PadraoMovimentacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='serase_app.padraomovimentacao'),
        ),
    ]
