# Generated by Django 3.1.3 on 2020-11-12 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serase_app', '0009_auto_20201111_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padraomovimentacao',
            name='receita_despesa',
            field=models.CharField(choices=[('R', 'Receita'), ('D', 'Despesa')], max_length=1),
        ),
    ]
