# Generated by Django 3.1.3 on 2020-11-13 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serase_app', '0010_auto_20201112_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padraomovimentacao',
            name='receita_despesa',
            field=models.CharField(choices=[('Receita', 'Receita'), ('Despesa', 'Despesa')], max_length=7),
        ),
    ]
