# Generated by Django 3.1.5 on 2021-01-22 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serase_app', '0013_auto_20210108_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padraomovimentacao',
            name='receita_despesa',
            field=models.CharField(choices=[('receita', 'receita'), ('despesa', 'despesa'), ('divida', 'divida')], max_length=7),
        ),
        migrations.CreateModel(
            name='Divida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credor', models.CharField(blank=True, max_length=40, null=True)),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('valor_divida', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('juros', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('juros_tipo', models.CharField(choices=[('composto', 'composto'), ('simples', 'simples')], max_length=8)),
                ('juros_ativos', models.BooleanField(default=False)),
                ('cod_padrao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='serase_app.padraomovimentacao')),
            ],
        ),
    ]
