# Generated by Django 2.2.16 on 2021-03-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serase_app', '0015_auto_20210312_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padraomovimentacao',
            name='periodo',
            field=models.CharField(choices=[('semanal', 'semanal'), ('mensal', 'mensal'), ('anual', 'anual')], max_length=7),
        ),
    ]
