# Generated by Django 2.2.16 on 2021-03-15 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serase_app', '0016_auto_20210312_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='padraomovimentacao',
            old_name='data_inicio',
            new_name='data_geracao',
        ),
    ]
