# Generated by Django 2.2.16 on 2021-03-18 00:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serase_app', '0018_auto_20210315_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padraomovimentacao',
            name='data_geracao',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
